#!/bin/bash

git add * 

if [ -T $@ ]
then
	git commit -m "$@"
else
	git commit -m "hot fix"
fi

echo "do u want to push now"
read $x

if [ $x=="y" ]
then
	git push
	echo "ok"
	exit
else
	echo "ok, boss"
	exit
fi